spring.application.name=birthday-backend
server.port=${PORT:9093}

# Fallback values if environment variables are not set
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:JBdEzRVmpMbwyBKncvpbmhFyMqnyJOnw}

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true